# Generated by Django 4.1.2 on 2022-10-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_class_rename_teachermodel_teacher_delete_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='nome',
            new_name='name',
        ),
    ]
